export const ActionTypes = {
    SET_FETCH_ERROR: "SET_FETCH_ERROR",

<<<<<<< HEAD
    SET_USERS: "SET_USERS",
    SET_SELECTED_USER: "SET_SELECTED_USER",
    
    SET_GUESTS: "SET_GUESTS",
    SET_SELECTED_GUESTS: "SET_SELECTED_GUESTS",

    SET_ROOMS: "SET_ROOMS",
    SET_SELECTED_SET_ROOM: "SET_SELECTED_SET_ROOM",

    SET_RESERVATIONS: "SET_RESERVATIONS",
    SET_SELECTED_RESERVATION: "SET_SELECTED_RESERVATION",

    SET_POS: "SET_POS",
     SET_POS_STATS: "SET_POS_STATS",
    SET_SELECTED_POS: "SET_SELECTED_POS",

    SET_BILLS: "SET_BILLS",
    SET_SELECTED_BILL: "SET_SELECTED_BILL",
=======
    SET_USERS: "SET_USERS", 
    SET_GUESTS: "SET_GUESTS",
    SET_SELECTED_USER: "SET_SELECTED_USER", 
    SET_SELECTED_GUESTS: "SET_SELECTED_GUESTS",
  
>>>>>>> 9caa6e2523b37c39dbada7f3aa7fdcd1ee386a6f
}