export const ActionTypes = {
    SET_FETCH_ERROR: "SET_FETCH_ERROR",

    SET_USERS: "SET_USERS",
    SET_SELECTED_USER: "SET_SELECTED_USER",
    
    SET_GUESTS: "SET_GUESTS",
    SET_SELECTED_GUESTS: "SET_SELECTED_GUESTS",

    SET_ROOMS: "SET_ROOMS",
    SET_SELECTED_SET_ROOM: "SET_SELECTED_SET_ROOM",

    SET_RESERVATIONS: "SET_RESERVATIONS",
    SET_SELECTED_RESERVATION: "SET_SELECTED_RESERVATION",

    SET_POS: "SET_POS",
    SET_POS_STATS: "SET_POS_STATS",
    SET_SELECTED_POS: "SET_SELECTED_POS",

    SET_PRODUCTS: "SET_PRODUCTS",
    SET_SELECTED_PRODUCT: "SET_SELECTED_PRODUCT",

    SET_CATEGORY: "SET_CATEGORY",
    SET_ORDERS: "SET_ORDERS",
    SET_SELECTED_ORDER: "SET_SELECTED_ORDER",
    SET_ORDER_ITEMS: "SET_ORDER_ITEMS",
    SET_ORDER_ITEM: "SET_ORDER_ITEM",

    SET_BILLS: "SET_BILLS",
    SET_SELECTED_BILL: "SET_SELECTED_BILL",
}